name       : mylg
version    : 0.2.6
release    : 2
source     :
    - https://solus-project.com/sources/golang-revendor/mylg-v0.2.6.tar.xz : 1c0b70cfb887e0ab1091173b26f7f47ce2a7f53df71815d78004edbc0c385e47
license    : MIT
component  : network.util
summary    : Command line Network Diagnostic Tool
description: |
    Software utility which combines the functions of the different network probes in one network diagnostic tool.
builddeps  :
    - golang
    - libpcap-devel
install    : |
    export GOPATH=`pwd`

    go build -v src/github.com/mehrdadrad/mylg/mylg.go
    install -Dm00755 mylg $installdir/usr/bin/mylg
